"""create services table

Revision ID: ddec6189b696
Revises: cf40d53739ae
Create Date: 2026-09-26 23:57:23.988554

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddec6189b696"
down_revision: str | Sequence[str] | None = "cf40d53739ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("buffer_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "buffer_minutes BETWEEN 0 AND 120 AND mod(buffer_minutes, 5) = 0",
            name=op.f("ck_services_buffer_valid"),
        ),
        sa.CheckConstraint(
            "duration_minutes BETWEEN 15 AND 480 AND mod(duration_minutes, 15) = 0",
            name=op.f("ck_services_duration_valid"),
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_services_price_not_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("services")
    # ### end Alembic commands ###
