"""create availability and time off tables

Revision ID: f9c65b95945d
Revises: 3874939def5f
Create Date: 2026-09-27 00:01:38.855750

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9c65b95945d"
down_revision: str | Sequence[str] | None = "3874939def5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_windows",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "end_time > start_time", name=op.f("ck_availability_windows_time_order")
        ),
        sa.CheckConstraint(
            "mod(extract(minute from end_time)::int, 15) = 0 AND extract(second from end_time) = 0",
            name=op.f("ck_availability_windows_end_on_grid"),
        ),
        sa.CheckConstraint(
            "mod(extract(minute from start_time)::int, 15) = 0 AND extract(second from start_time) = 0",
            name=op.f("ck_availability_windows_start_on_grid"),
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 0 AND 6", name=op.f("ck_availability_windows_weekday_valid")
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_availability_windows_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_windows")),
    )
    op.create_index(
        "ix_availability_windows_provider_weekday",
        "availability_windows",
        ["provider_id", "weekday"],
        unique=False,
    )
    op.create_table(
        "time_off",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_time_off_time_order")),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_time_off_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_off")),
    )
    op.create_index(
        "ix_time_off_provider_starts", "time_off", ["provider_id", "starts_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_time_off_provider_starts", table_name="time_off")
    op.drop_table("time_off")
    op.drop_index("ix_availability_windows_provider_weekday", table_name="availability_windows")
    op.drop_table("availability_windows")
    # ### end Alembic commands ###
